development:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password: ce

test:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password: ce

production:
 database: <%= ENV['RDS_DB_NAME'] %>
 username: <%= ENV['RDS_USERNAME'] %>
 password: <%= ENV['RDS_PASSWORD'] %>
 host: <%= ENV['RDS_HOSTNAME'] %>
 port: <%= ENV['RDS_PORT'] %>