evelopment:
  adapter: postgresql
  encoding: unicode
  database: ce_development
  pool: 5
  username: ce_postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ce_test
  pool: 5
  username: ce_postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ce_production
  pool: 5
  username: ce_postgres
  password: