# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c5cf350ba348cb52aae3b8b2e505377a3fefcbcfac5938ce78757aba345b11e67b756811e4707dfde8e75a24869f65477aa0b493f7ab73f4ae2a9493b5bfc99

test:
  secret_key_base: 65475b27bc95e4ab962a8b1ea51b33615d58f6b6fa928188e6a8f558cb1b5d337f593410d0f5cf4bdf32a8ff165e7569986fa39fdeb5923b4564daa6cad76de7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
